<?php

namespace AppBundle\Repository;

/**
 * PcharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
