<?php

namespace PX\EasypackBundle\Repository;

/**
 * ClientHasCarrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientHasCarrierRepository extends \Doctrine\ORM\EntityRepository
{


    public function customFindBy()
    {

        $qb = $this->createQueryBuilder('mbt')
            ->select('mbt')
            ->from('PXEasypackBundle:Carrier', 'mbc');

        $qb->where('mbc INSTANCE OF PX\EasypackBundle\Entity\Carrier\Imx');



        $query = $qb->getQuery();
        return $query->getResult();
    }

}
