<?php

namespace PX\EasypackBundle\Repository;

/**
 * SenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenderRepository extends \Doctrine\ORM\EntityRepository
{
}
